version: '3.8'

services:
  backend:
    build: ./backend/
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
    healthcheck:
      test: curl -s http://localhost:3000
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 1s